/* =========================================
   K&K — Czas na Wycisk!
   BAZA ĆWICZEŃ — BRZUCH / CORE
   core.js
   v1.1
   ========================================= */

const coreExercises = [

  {
    id: "crunch",
    name: "Spięcia brzucha",
    primaryBodyPart: "abs",
    secondaryBodyParts: [],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "trunk-flexion",
    movementTags: ["crunch"],
    workoutRole: "secondary",
    fatigue: 2,
    timed: false,
    repRange: { min: 12, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 150,
    instructions: "Połóż się na plecach, ugnij kolana i oprzyj stopy o podłoże. Napnij brzuch i unieś górną część pleców, kierując żebra w stronę miednicy. Nie ciągnij głowy rękami i nie odrywaj dolnej części pleców od podłoża.",
    videoUrl: "https://www.youtube.com/shorts/Dbr2J9375oo"
  },

  {
    id: "reverse-crunch",
    name: "Odwrotne spięcia brzucha",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "pelvic-flexion",
    movementTags: ["reverse-crunch"],
    workoutRole: "secondary",
    fatigue: 2,
    timed: false,
    repRange: { min: 10, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 150,
    instructions: "Połóż się na plecach i unieś nogi z kolanami ugiętymi około 90 stopni. Przyciągnij kolana w kierunku klatki i lekko podwiń miednicę. Nie wykonuj ruchu z zamachu.",
    videoUrl: "https://www.youtube.com/shorts/eX9vjAsdWvY"
  },

  {
    id: "leg-raise",
    name: "Unoszenie nóg leżąc",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "hip-flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "hip-flexion",
    movementTags: ["lying-leg-raise"],
    workoutRole: "main",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 45, max: 75 },
    estimatedSeconds: 180,
    instructions: "Połóż się na plecach z wyprostowanymi nogami. Unieś nogi do góry, utrzymując napięty brzuch i dolną część pleców możliwie blisko podłoża. Opuszczaj nogi powoli i tylko tak nisko, jak pozwala zachować prawidłową pozycję pleców.",
    videoUrl: "https://www.youtube.com/shorts/FijNSgahpz0"
  },

  {
    id: "plank",
    name: "Deska",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "glutes", "back"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "anti-extension",
    movementTags: ["plank", "isometric"],
    workoutRole: "main",
    fatigue: 2,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 60 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Oprzyj przedramiona i palce stóp o podłoże. Utrzymuj ciało w jednej linii, napnij brzuch i pośladki. Nie pozwalaj biodrom opadać ani unosić się zbyt wysoko.",
    videoUrl: "https://www.youtube.com/shorts/xe2MXatLTUw"
  },

  {
    id: "bicycle-crunch",
    name: "Brzuszki rowerowe",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-rotation",
    movementTags: ["crunch", "rotation", "alternating"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 10, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się na plecach i unieś nogi. Przyciągaj jedno kolano do klatki, jednocześnie obracając tułów tak, aby przeciwny łokieć zbliżał się do kolana. Zmieniaj strony płynnie i kontrolowanie.",
    videoUrl: "https://www.youtube.com/shorts/_I2Fiy7ueNw"
  },

  {
    id: "russian-twist",
    name: "Skręty tułowia w siadzie",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "back"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-rotation",
    movementTags: ["russian-twist"],
    workoutRole: "secondary",
    fatigue: 2,
    timed: false,
    repRange: { min: 10, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Usiądź z ugiętymi kolanami i lekko odchyl tułów. Obracaj klatkę piersiową naprzemiennie w lewo i w prawo. Utrzymuj napięty brzuch i nie wykonuj ruchu jedynie ramionami.",
    videoUrl: "https://www.youtube.com/shorts/-cPtvFdT8dc"
  },

  {
    id: "side-plank",
    name: "Deska bokiem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-lateral-flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-lateral-flexion",
    movementTags: ["side-plank", "isometric"],
    workoutRole: "main",
    fatigue: 2,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 45 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Oprzyj przedramię pod barkiem i unieś biodra. Utrzymuj ciało w jednej linii, nie pozwalając biodrom opadać ani obracać się do przodu. Po wykonaniu czasu zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/BFOyHDlY2UE"
  },

  {
    id: "mountain-climber",
    name: "Mountain climbers",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "hip-flexors", "legs"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "dynamic-hip-flexion",
    movementTags: ["plank", "conditioning"],
    workoutRole: "finisher",
    fatigue: 3,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 40 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w wysokiej desce. Naprzemiennie przyciągaj kolana w kierunku klatki piersiowej, zachowując stabilne biodra i napięty brzuch.",
    videoUrl: "https://www.youtube.com/shorts/1wDQznFSh3E"
  },

  {
    id: "bird-dog",
    name: "Bird dog",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["back", "glutes", "shoulders"],
    strongSecondaryBodyParts: ["back", "glutes"],
    coreFunction: "anti-rotation",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "contralateral-stability",
    movementTags: ["bird-dog", "contralateral", "stability"],
    workoutRole: "main",
    fatigue: 1,
    timed: false,
    repRange: { min: 8, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 150,
    instructions: "Ustaw się w klęku podpartym. Napnij brzuch i jednocześnie wyprostuj przeciwną rękę oraz nogę, utrzymując biodra i tułów nieruchomo. Wróć kontrolowanie do pozycji wyjściowej i zmień stronę.",
    videoUrl: ""
  },

  {
    id: "dead-bug",
    name: "Dead bug",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "back"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "anti-extension",
    movementTags: ["dead-bug", "contralateral"],
    workoutRole: "main",
    fatigue: 1,
    timed: false,
    repRange: { min: 8, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 150,
    instructions: "Połóż się na plecach, unieś nogi z kolanami około 90 stopni i wyprostuj ręce nad klatką. Dociśnij lędźwie do podłoża. Opuszczaj jednocześnie przeciwną rękę i nogę bez utraty napięcia brzucha.",
    videoUrl: "https://www.youtube.com/shorts/DqLL45uk2Tk"
  },

  {
    id: "hollow-body-hold",
    name: "Hollow body hold",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-extension",
    movementTags: ["hollow-body", "isometric"],
    workoutRole: "main",
    fatigue: 2,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 40 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się na plecach i dociśnij odcinek lędźwiowy do podłoża. Unieś łopatki i nogi nad ziemię. Utrzymuj napięcie bez odrywania dolnej części pleców.",
    videoUrl: "https://www.youtube.com/shorts/YHBp6fvXYcI"
  },

  {
    id: "flutter-kicks",
    name: "Nożyce pionowe",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "alternating-hip-flexion",
    movementTags: ["flutter-kicks"],
    workoutRole: "accessory",
    fatigue: 2,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 40 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się na plecach, unieś wyprostowane nogi nad podłoże i wykonuj krótkie naprzemienne ruchy góra-dół. Utrzymuj napięty brzuch i dolną część pleców przy ziemi.",
    videoUrl: "https://www.youtube.com/shorts/Cz6iXfmgtiw"
  },

  {
    id: "heel-taps",
    name: "Dotykanie pięt w leżeniu",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "lateral-flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "lateral-flexion",
    movementTags: ["heel-taps"],
    workoutRole: "accessory",
    fatigue: 2,
    timed: false,
    repRange: { min: 12, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 150,
    instructions: "Połóż się na plecach z ugiętymi kolanami. Unieś lekko łopatki i wykonuj naprzemienne skłony boczne, sięgając dłonią w kierunku pięty po tej samej stronie.",
    videoUrl: "https://www.youtube.com/shorts/Fg4ryGff51M"
  },

  {
    id: "toe-touches",
    name: "Dotykanie palców stóp",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "trunk-flexion",
    movementTags: ["crunch", "legs-elevated"],
    workoutRole: "accessory",
    fatigue: 2,
    timed: false,
    repRange: { min: 12, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 150,
    instructions: "Połóż się na plecach i unieś nogi pionowo. Unieś łopatki, sięgając dłońmi w stronę stóp. Następnie kontrolowanie wróć, utrzymując nogi stabilnie.",
    videoUrl: "https://www.youtube.com/shorts/20P7MU4Oaec"
  },

  {
    id: "v-up",
    name: "V-ups",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 3,
    movementPattern: "trunk-and-hip-flexion",
    movementTags: ["v-up"],
    workoutRole: "main",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 45, max: 75 },
    estimatedSeconds: 180,
    instructions: "Leżąc na plecach jednocześnie unieś wyprostowane nogi i górną część tułowia, sięgając dłońmi w kierunku stóp. Nie używaj zamachu.",
    videoUrl: "https://www.youtube.com/shorts/saHkR_MvIdA"
  },

  {
    id: "seated-knee-tuck",
    name: "Przyciąganie kolan do klatki w siadzie",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "hip-flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-and-hip-flexion",
    movementTags: ["knee-tuck", "seated"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 10, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Usiądź, lekko odchyl tułów i unieś stopy. Przyciągnij kolana w stronę klatki, a następnie wyprostuj nogi bez odkładania ich na podłoże.",
    videoUrl: "https://www.youtube.com/shorts/x2umFUuBLRw"
  },

  {
    id: "hanging-knee-raise",
    name: "Unoszenie kolan w zwisie",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "forearms", "shoulders"],
    strongSecondaryBodyParts: [],
    coreFunction: "hip-flexion",
    requiredEquipment: [{ type: "pull-up-bar", quantity: 1 }, { type: "bodyweight", quantity: 1 }],
    equipmentConditions: ["bar-high"],
    difficulty: 2,
    movementPattern: "hanging-hip-flexion",
    movementTags: ["hanging", "knee-raise"],
    workoutRole: "main",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 45, max: 90 },
    estimatedSeconds: 180,
    instructions: "Zawiśnij na drążku i ogranicz kołysanie. Przyciągnij kolana do klatki, lekko podwijając miednicę. Następnie kontrolowanie opuść nogi.",
    videoUrl: "https://www.youtube.com/shorts/menMCCf0PbE"
  },

  {
    id: "hanging-leg-raise",
    name: "Unoszenie prostych nóg w zwisie",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "forearms", "shoulders"],
    strongSecondaryBodyParts: [],
    coreFunction: "hip-flexion",
    requiredEquipment: [{ type: "pull-up-bar", quantity: 1 }, { type: "bodyweight", quantity: 1 }],
    equipmentConditions: ["bar-high"],
    difficulty: 3,
    movementPattern: "hanging-hip-flexion",
    movementTags: ["hanging", "straight-leg-raise"],
    workoutRole: "main",
    fatigue: 4,
    timed: false,
    repRange: { min: 6, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 60, max: 90 },
    estimatedSeconds: 210,
    instructions: "Zawiśnij stabilnie na drążku. Unieś możliwie wyprostowane nogi przed siebie co najmniej do wysokości bioder. Kontrolowanie opuść je bez rozpędzania ciała.",
    videoUrl: "https://www.youtube.com/shorts/Z9ryXTU4FBQ"
  },

  {
    id: "plank-shoulder-tap",
    name: "Deska z dotykaniem barków",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "triceps", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-rotation",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-rotation",
    movementTags: ["plank", "shoulder-tap"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 16 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w wysokiej desce. Oderwij jedną dłoń i dotknij przeciwnego barku, starając się nie obracać bioder. Powtórz drugą stroną.",
    videoUrl: "https://www.youtube.com/shorts/VfwCQ14soUo"
  },

  {
    id: "plank-knee-to-elbow",
    name: "Deska z przyciąganiem kolana do łokcia",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "hip-flexors", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "plank-hip-flexion",
    movementTags: ["plank", "knee-to-elbow"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w wysokiej desce. Przyciągnij kolano w kierunku łokcia po tej samej stronie, zachowując stabilny tułów. Wróć i zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/vhnQR5lCF-U"
  },

  {
    id: "plank-hip-dip",
    name: "Deska bokiem z opuszczaniem bioder",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "lateral-flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "lateral-flexion",
    movementTags: ["side-plank", "hip-dip"],
    workoutRole: "accessory",
    fatigue: 2,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w desce bokiem. Kontrolowanie opuść biodra w kierunku podłoża, a następnie unieś je z powrotem. Po serii zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/fZ9PoqS-Yi0"
  },

  {
    id: "plank-walkout",
    name: "Wyjścia z podporu do deski",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "triceps", "back"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-extension",
    movementTags: ["walkout", "plank"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 6, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Pochyl się i oprzyj dłonie o podłoże. Przesuwaj je do przodu aż do wysokiej deski. Utrzymaj napięty brzuch, a następnie wróć dłońmi w kierunku stóp.",
    videoUrl: "https://www.youtube.com/shorts/AU9X0HVJCPI"
  },

  {
    id: "resistance-band-woodchop",
    name: "Ściąganie długiej gumy po skosie",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "back", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "resistance-band", quantity: 1 }],
    equipmentConditions: ["anchor-high"],
    difficulty: 2,
    movementPattern: "trunk-rotation",
    movementTags: ["woodchop", "diagonal", "band"],
    workoutRole: "main",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Zamocuj długą gumę oporową wysoko z boku. Chwyć ją oburącz i prowadź po skosie w dół w kierunku przeciwnego biodra, obracając tułów kontrolowanie. Po serii zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/64RP6a4zK7Q"
  },

  {
    id: "weighted-russian-twist-dumbbell",
    name: "Skręty tułowia z hantlem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "shoulders"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "dumbbells", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-rotation",
    movementTags: ["russian-twist", "weighted"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 10, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Usiądź i lekko odchyl tułów. Trzymaj jeden hantel oburącz przed klatką i obracaj tułów naprzemiennie na obie strony.",
    videoUrl: "https://www.youtube.com/shorts/aRUMRbl7KS4"
  },

  {
    id: "kettlebell-russian-twist",
    name: "Skręty tułowia z kettlebell",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "shoulders"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "kettlebell", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-rotation",
    movementTags: ["russian-twist", "weighted"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 10, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Usiądź i lekko odchyl tułów. Trzymaj kettlebell oburącz przed klatką i obracaj tułów naprzemiennie na obie strony.",
    videoUrl: "https://www.youtube.com/shorts/rTTBzWIsUIM"
  },

  {
    id: "dumbbell-side-bend",
    name: "Skłony boczne z hantlem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["forearms"],
    strongSecondaryBodyParts: [],
    coreFunction: "lateral-flexion",
    requiredEquipment: [{ type: "dumbbells", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "lateral-flexion",
    movementTags: ["side-bend", "weighted", "unilateral"],
    workoutRole: "accessory",
    fatigue: 2,
    timed: false,
    repRange: { min: 10, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Trzymaj jeden hantel przy boku. Wykonaj kontrolowany skłon tułowia w bok, a następnie wróć do pionu. Po serii zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/44DazvtgpGE"
  },

  {
    id: "kettlebell-side-bend",
    name: "Skłony boczne z kettlebell",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["forearms"],
    strongSecondaryBodyParts: [],
    coreFunction: "lateral-flexion",
    requiredEquipment: [{ type: "kettlebell", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 1,
    movementPattern: "lateral-flexion",
    movementTags: ["side-bend", "weighted", "unilateral"],
    workoutRole: "accessory",
    fatigue: 2,
    timed: false,
    repRange: { min: 10, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Trzymaj kettlebell w jednej dłoni przy boku. Wykonaj kontrolowany skłon tułowia w bok, a następnie wróć do pionu. Po serii zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/Rl_MsU1yI44"
  },

  {
    id: "suitcase-carry",
    name: "Spacer farmera jednorącz z ciężarem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["forearms", "shoulders", "back", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-lateral-flexion",
    requiredEquipment: [],
    equipmentOptions: [
      [{ type: "dumbbells", quantity: 1 }],
      [{ type: "kettlebell", quantity: 1 }]
    ],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "loaded-carry",
    movementTags: ["carry", "unilateral", "anti-lateral-flexion"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 45 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Trzymaj hantel albo kettlebell w jednej dłoni. Maszeruj, utrzymując pionowy tułów i nie pozwalając ciężarowi przechylać ciała. Po czasie zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/w76_JnzMfXM"
  },

  {
    id: "farmer-carry",
    name: "Spacer farmera z ciężarami",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["forearms", "shoulders", "back", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [],
    equipmentOptions: [
      [{ type: "dumbbells", quantity: 2 }],
      [{ type: "kettlebell", quantity: 2 }]
    ],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "loaded-carry",
    movementTags: ["carry", "bilateral"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 45 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Trzymaj dwa hantle albo dwa kettlebell po bokach ciała. Maszeruj kontrolowanie, utrzymując napięty brzuch, stabilny tułów i wyprostowaną sylwetkę.",
    videoUrl: "https://www.youtube.com/shorts/Ozp9nI_w4xo"
  },

  {
    id: "plank-dumbbell-drag",
    name: "Deska z przeciąganiem hantla",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "triceps", "back", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-rotation",
    requiredEquipment: [{ type: "dumbbells", quantity: 1 }, { type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-rotation",
    movementTags: ["plank", "drag", "weighted"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 6, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w wysokiej desce z hantlem obok dłoni. Przeciągnij ciężar pod tułowiem na drugą stronę, starając się nie obracać bioder. Powtarzaj naprzemiennie.",
    videoUrl: "https://www.youtube.com/shorts/5gR0_CcEYvw"
  },

  {
    id: "plank-kettlebell-drag",
    name: "Deska z przeciąganiem kettlebell",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "triceps", "back", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-rotation",
    requiredEquipment: [{ type: "kettlebell", quantity: 1 }, { type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-rotation",
    movementTags: ["plank", "drag", "weighted"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 6, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w wysokiej desce z kettlebell obok dłoni. Przeciągnij ciężar pod tułowiem na drugą stronę bez rotowania bioder. Powtarzaj naprzemiennie.",
    videoUrl: "https://www.youtube.com/shorts/Vk3qLh6QywM"
  },

  {
    id: "hollow-body-rock",
    name: "Kołyski w pozycji hollow body",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 3,
    movementPattern: "anti-extension",
    movementTags: ["hollow-body", "rock"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 10, max: 20 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Przyjmij pozycję hollow body. Zachowując niezmienny kształt ciała, wykonuj niewielkie kontrolowane kołyski do przodu i do tyłu.",
    videoUrl: "https://www.youtube.com/shorts/tWZBamV2tjc"
  },

  {
    id: "dead-bug-dumbbell",
    name: "Dead bug z hantlem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "dumbbells", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-extension",
    movementTags: ["dead-bug", "weighted"],
    workoutRole: "secondary",
    fatigue: 2,
    timed: false,
    repRange: { min: 8, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się na plecach i trzymaj lekki hantel nad klatką. Utrzymuj lędźwie przy podłożu i naprzemiennie opuszczaj nogę w kierunku ziemi bez utraty napięcia brzucha.",
    videoUrl: "https://www.youtube.com/shorts/VAVrsPX9GHY"
  },

  {
    id: "kettlebell-dead-bug-hold",
    name: "Dead bug z kettlebell trzymanym nad klatką",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "kettlebell", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-extension",
    movementTags: ["dead-bug", "weighted"],
    workoutRole: "secondary",
    fatigue: 2,
    timed: false,
    repRange: { min: 8, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się na plecach i trzymaj kettlebell oburącz nad klatką. Dociśnij dolną część pleców do ziemi i naprzemiennie opuszczaj nogi bez poruszania ciężarem.",
    videoUrl: "https://www.youtube.com/shorts/El5o_avIaqI"
  },

  {
    id: "weighted-crunch-dumbbell",
    name: "Spięcia brzucha z hantlem",
    primaryBodyPart: "abs",
    secondaryBodyParts: [],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "dumbbells", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-flexion",
    movementTags: ["crunch", "weighted"],
    workoutRole: "secondary",
    fatigue: 2,
    timed: false,
    repRange: { min: 10, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Leżąc z ugiętymi kolanami trzymaj hantel przy klatce. Unieś górną część pleców, kierując żebra w stronę miednicy. Nie wykonuj ruchu z zamachu.",
    videoUrl: "https://www.youtube.com/shorts/G9XfQJPBJVI"
  },

  {
    id: "weighted-crunch-kettlebell",
    name: "Spięcia brzucha z kettlebell",
    primaryBodyPart: "abs",
    secondaryBodyParts: [],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "kettlebell", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-flexion",
    movementTags: ["crunch", "weighted"],
    workoutRole: "secondary",
    fatigue: 2,
    timed: false,
    repRange: { min: 10, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Leżąc z ugiętymi kolanami trzymaj kettlebell oburącz przy klatce. Unieś górną część pleców, kierując żebra w stronę miednicy. Kontrolowanie wróć.",
    videoUrl: "https://www.youtube.com/shorts/JkaEmrdtyoA"
  },

  {
    id: "weighted-sit-up-dumbbell",
    name: "Brzuszki z hantlem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "dumbbells", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-and-hip-flexion",
    movementTags: ["sit-up", "weighted"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się z ugiętymi kolanami i trzymaj hantel przy klatce. Unieś tułów do pozycji siedzącej bez używania zamachu, a następnie powoli wróć.",
    videoUrl: "https://www.youtube.com/shorts/nAaLDMzlAMQ"
  },

  {
    id: "weighted-sit-up-kettlebell",
    name: "Brzuszki z kettlebell",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "kettlebell", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-and-hip-flexion",
    movementTags: ["sit-up", "weighted"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się z ugiętymi kolanami i trzymaj kettlebell przy klatce. Unieś tułów do pozycji siedzącej bez zamachu, a następnie kontrolowanie wróć.",
    videoUrl: "https://www.youtube.com/shorts/Eu5c4VBuS80"
  },

  {
    id: "lying-windshield-wipers",
    name: "Wycieraczki nóg w leżeniu",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "back"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 3,
    movementPattern: "trunk-rotation",
    movementTags: ["windshield-wipers", "lying"],
    workoutRole: "main",
    fatigue: 3,
    timed: false,
    repRange: { min: 6, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 45, max: 75 },
    estimatedSeconds: 180,
    instructions: "Połóż się na plecach i rozłóż ramiona na boki. Unieś nogi i kontrolowanie opuszczaj je raz na jedną, raz na drugą stronę, nie odrywając barków od podłoża.",
    videoUrl: "https://www.youtube.com/shorts/CZS3m8zBVSA"
  },

  {
    id: "hanging-oblique-knee-raise",
    name: "Unoszenie kolan w zwisie po skosie",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "forearms", "shoulders"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "pull-up-bar", quantity: 1 }, { type: "bodyweight", quantity: 1 }],
    equipmentConditions: ["bar-high"],
    difficulty: 3,
    movementPattern: "hanging-rotation",
    movementTags: ["hanging", "knee-raise", "rotation"],
    workoutRole: "main",
    fatigue: 3,
    timed: false,
    repRange: { min: 6, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 45, max: 90 },
    estimatedSeconds: 210,
    instructions: "Zawiśnij na drążku. Przyciągnij kolana w kierunku jednej strony klatki, lekko skręcając miednicę. Wróć i wykonaj ruch na drugą stronę.",
    videoUrl: "https://www.youtube.com/shorts/UBL5xMB4Pa4"
  },

  {
    id: "hanging-windshield-wipers",
    name: "Wycieraczki nóg w zwisie",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors", "forearms", "shoulders", "back"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "pull-up-bar", quantity: 1 }, { type: "bodyweight", quantity: 1 }],
    equipmentConditions: ["bar-high"],
    difficulty: 4,
    movementPattern: "hanging-rotation",
    movementTags: ["hanging", "windshield-wipers", "advanced"],
    workoutRole: "secondary",
    fatigue: 4,
    timed: false,
    repRange: { min: 4, max: 8 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 60, max: 120 },
    estimatedSeconds: 240,
    instructions: "Zawiśnij stabilnie na drążku i unieś nogi przed siebie. Prowadź je kontrolowanie na jedną i drugą stronę bez używania zamachu. Dobierz zakres ruchu do swoich możliwości.",
    videoUrl: "https://youtube.com/shorts/xvw_r7VZ2S8"
  },

  {
    id: "bear-plank",
    name: "Deska niedźwiedzia",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "triceps", "legs"],
    strongSecondaryBodyParts: [],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "anti-extension",
    movementTags: ["bear-position", "isometric"],
    workoutRole: "main",
    fatigue: 3,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 40 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się na dłoniach i kolanach, a następnie unieś kolana kilka centymetrów nad podłoże. Utrzymuj napięty brzuch, neutralne plecy i stabilne biodra.",
    videoUrl: "https://www.youtube.com/shorts/M1LgdyUDLsc"
  },

  {
    id: "bear-crawl",
    name: "Chód niedźwiedzia",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "triceps", "legs", "glutes"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "locomotion",
    movementTags: ["bear-position", "conditioning", "contralateral"],
    workoutRole: "finisher",
    fatigue: 3,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 40 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w pozycji niedźwiedzia z kolanami nad ziemią. Przemieszczaj się małymi krokami, poruszając jednocześnie przeciwną ręką i nogą. Ogranicz kołysanie tułowia.",
    videoUrl: "https://www.youtube.com/shorts/iuR17xUXLeA"
  },

  {
    id: "cross-body-mountain-climber",
    name: "Mountain climbers ze skrętem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "hip-flexors", "legs"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "dynamic-rotation",
    movementTags: ["mountain-climber", "rotation", "conditioning"],
    workoutRole: "finisher",
    fatigue: 3,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 40 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w wysokiej desce. Naprzemiennie przyciągaj kolano w kierunku przeciwnego łokcia, lekko rotując tułów i utrzymując kontrolę bioder.",
    videoUrl: "https://www.youtube.com/shorts/UDPHAuf9I2k"
  },

  {
    id: "side-plank-reach-through",
    name: "Deska bokiem z przełożeniem ręki pod tułowiem",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "glutes", "back"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-rotation",
    movementTags: ["side-plank", "rotation"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w desce bokiem. Przeprowadź wolną rękę pod tułowiem, lekko rotując klatkę, a następnie otwórz ją z powrotem. Po serii zmień stronę.",
    videoUrl: "https://www.youtube.com/shorts/46hHgDE1Z80"
  },

  {
    id: "straight-leg-sit-up",
    name: "Brzuszki z prostymi nogami",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "flexion",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "trunk-and-hip-flexion",
    movementTags: ["sit-up", "straight-legs"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Połóż się z nogami wyprostowanymi. Unieś tułów do pozycji siedzącej bez gwałtownego zamachu ramion, a następnie kontrolowanie wróć do leżenia.",
    videoUrl: "https://www.youtube.com/shorts/z0GiuqW9t5U"
  },

  {
    id: "reverse-plank",
    name: "Deska odwrócona",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["glutes", "hamstrings", "shoulders", "triceps"],
    strongSecondaryBodyParts: ["glutes", "legs"],
    coreFunction: "anti-extension",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "posterior-chain-isometric",
    movementTags: ["reverse-plank", "hip-extension", "isometric"],
    workoutRole: "accessory",
    fatigue: 2,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 45 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Usiądź z wyprostowanymi nogami i oprzyj dłonie za sobą. Unieś biodra, tworząc możliwie prostą linię od barków do pięt. Napnij brzuch i pośladki.",
    videoUrl: "https://www.youtube.com/shorts/q37j_H0g5BY"
  },

  {
    id: "hollow-body-knee-tuck",
    name: "Przyciąganie kolan w pozycji hollow body",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "hollow-body-hip-flexion",
    movementTags: ["hollow-body", "knee-tuck"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 15 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Przyjmij pozycję hollow body. Przyciągnij kolana do klatki bez utraty napięcia brzucha, a następnie ponownie wyprostuj nogi przed siebie.",
    videoUrl: "https://www.youtube.com/shorts/UKeSJFUz2L4"
  },

  {
    id: "plank-jack",
    name: "Deska z pajacykami nóg",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["shoulders", "glutes", "legs"],
    strongSecondaryBodyParts: [],
    coreFunction: "dynamic-stability",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 2,
    movementPattern: "dynamic-plank",
    movementTags: ["plank", "conditioning"],
    workoutRole: "finisher",
    fatigue: 3,
    timed: true,
    repRange: null,
    timeRange: { min: 20, max: 40 },
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Ustaw się w wysokiej desce. Dynamicznie rozsuwaj i złączaj stopy jak przy pajacykach, utrzymując możliwie nieruchomy tułów i napięty brzuch.",
    videoUrl: "https://www.youtube.com/shorts/kjvqHqVvUME"
  },

  {
    id: "alternating-v-up",
    name: "Naprzemienne V-ups",
    primaryBodyPart: "abs",
    secondaryBodyParts: ["hip-flexors"],
    strongSecondaryBodyParts: [],
    coreFunction: "rotation",
    requiredEquipment: [{ type: "bodyweight", quantity: 1 }],
    equipmentConditions: [],
    difficulty: 3,
    movementPattern: "trunk-and-hip-flexion",
    movementTags: ["v-up", "alternating", "rotation"],
    workoutRole: "secondary",
    fatigue: 3,
    timed: false,
    repRange: { min: 8, max: 12 },
    timeRange: null,
    setRange: { min: 2, max: 4 },
    restRange: { min: 30, max: 60 },
    estimatedSeconds: 180,
    instructions: "Leżąc na plecach unieś jedną nogę oraz przeciwną rękę i zbliż dłoń do stopy. Wróć kontrolowanie i wykonaj ruch drugą stroną.",
    videoUrl: "https://www.youtube.com/shorts/-ipF-Xl5eY4"
  }

];

/* =========================================
   UDOSTĘPNIENIE MODUŁU
   ========================================= */

window.CoreExercises = coreExercises;